[build]
    publish="dist"
    functions="src/functions"
[dev]
    publish="dist"
    functions="src/functions"

[dev.environment]
    db_host = "value"
    db_user = "value"
    db_password = "value"
    database_name = "value"

[[redirects]]
    from = "/get-students"
    to = "/.netlify/functions/getStudents/getStudents.js"
    status = 200
[[redirects]]
    from = "/add-new-student"
    to = "/.netlify/functions/addNewStudent/addNewStudent.js"
    status = 200
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200