[build]
    publish="dist"
    functions="src/functions"
[dev]
    publish="dist"
    functions="src/functions"

[dev.environment]
    db_host = "value"
    db_user = "value"
    db_password = "value"
    database_name = "value"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200